sclorg/s2i-php-container

5.5/Dockerfile
5.5/Dockerfile.rhel7

Since the mcrypt pkg is not part of php55 scl we can remove it.
@bparees PTAL

Remove misspelled mcrypt

---

5.5/Dockerfile.rhel7
5.6/Dockerfile.rhel7

It is recommended not to use MAINTAINER in RHEL images.

Remove MAINTAINER in RHEL image

---

5.5/contrib/etc/php.d/opcache.ini.template
5.6/contrib/etc/php.d/10-opcache.ini.template

Since 5.5, "zend_extension" don't requires full path, so safer to fix both 5.5 and 5.6

fix opcache config path, fix #62

---

5.5/contrib/etc/httpdconf.sed
5.6/contrib/etc/httpdconf.sed

I've configured Apache to use [piped logs](http://httpd.apache.org/docs/2.4/logs.html#piped) and now it's writing access logs to stdout instead of `/tmp/access_log`. This change addresses to https://bugzilla.redhat.com/show_bug.cgi?id=1231862
PTAL @rhcarvalho @mfojtik
I've tested in on with php55/php56 and CentOS7.
A couple of related questions:
1) now there is no `/tmp/access_log`. Is it ok or we should provide backward compatibility? If we should I think we may change `cat` to `tee` and it would work fine
2) (if the answer to the first question is "No") Should we update our documentation like we did in https://github.com/openshift/openshift-docs/pull/887?

Configure Apache to write access logs to stdout instead of file

---

5.5/README.md
5.6/README.md
README.md

This is similar to https://github.com/openshift/mysql/pull/99. It allows us to maintain two separate variant for every version (default values, image names, links to doc and eventually more, that may be or already is different). As a bonus, we'll have a clean `README.md` with only image-related usage information that can be used in Docker Hub or elsewhere.

Split README.md to usage and general part

---

5.5/Dockerfile
5.5/Dockerfile.rhel7
5.5/README.md
5.5/contrib/etc/conf.d/50-mpm-tuning.conf.template
5.5/s2i/bin/run
5.6/Dockerfile
5.6/Dockerfile.rhel7
5.6/README.md
5.6/contrib/etc/conf.d/50-mpm-tuning.conf.template
5.6/s2i/bin/run

This PR introduces tuning of MPM values for the httpd server. You can override the defaults by passing these environment variables when starting this container:
* `HTTPD_START_SERVERS` - sets the number of child server processes created on startup
* `HTTPD_MAX_REQUEST_WORKERS` - (former name: MaxClients), sets the limit on the number of simultaneous requests that will be served.
If you don't specify them, the defaults are set to 8 servers and 256 workers (apache default). If you set the `--memory`, then the workers are determined by: total_memory/15MB where the 15MB is a magic value of estimated httpd process size (with PHP and all extensions enabled).
Fixes: https://github.com/openshift/s2i-base/issues/69

Tune httpd MPM based on available memory in container

---

5.5/README.md
5.5/s2i/bin/assemble
5.6/README.md
5.6/s2i/bin/assemble

The new COMPOSER_MIRROR env var is added to PHP images to allow custom
Composer/Packagist mirror to be used during build process.
Signed-off-by: Vu Dinh <vdinh@redhat.com>

Add COMPOSER_MIRROR env var to allow Composer/Packagist mirror for PHP images

---

5.5/s2i/bin/assemble
5.6/s2i/bin/assemble

@bparees this have been used on 5.5 and 5.6 tags without issues, PTAL.
fixes https://github.com/sclorg/s2i-php-container/issues/106

Use mv instead cp to save space

---

5.5/cccp.yml
5.6/cccp.yml

This is for the purpose of building these container
on the CentOS Container pipeline.

Added cccp.yml files for centos container pipeline.

---

5.5/Dockerfile.rhel7
5.6/Dockerfile.rhel7

Enabling host repositories didn't work with docker 1.10 and newer inside OpenStack. It was fixed in latest rhel7 base release, so using 'rhel7' base image is required for RHEL CI. Postgresql PR - sclorg/postgresql-container#150
Also to enable repositories inside container running 'yum' first is required - see https://access.redhat.com/solutions/1443553 . Similar to sclorg/s2i-base-container#99 .
@hhorak @bparees Please take a look and merge.

Fix using subscription in container

---

5.6/Dockerfile
7.0/Dockerfile

For centos/ namespaced images use centos/ namespaced s2i base image. This image is based on https://github.com/sclorg/s2i-base-container/ and is built by coreservices-jenkins maintained by RHSCL team.
@hhorak @bparees Please take a look and merge.

Use centos/ namespaced s2i base image

---

5.6/s2i/bin/run
7.0/s2i/bin/run

Fix for PHP S2I Opcache configuration

---

5.6/README.md
5.6/s2i/bin/run
7.0/README.md
7.0/s2i/bin/run

Resolve #152 by setting default for Opcache Memory Consumption to 128MB on PHP5.6 and PHP7.0

Set default opcache.memory_consumption to 128MB

---

5.6/root/opt/app-root/etc/scl_enable
7.0/root/opt/app-root/etc/scl_enable

Similarly to https://github.com/sclorg/s2i-python-container/pull/209

Enable rh-nodejs6, so users can use npm for installing JavaScript stuff

---

5.6/README.md
5.6/s2i/bin/assemble
7.0/README.md
7.0/s2i/bin/assemble
7.1/README.md
7.1/s2i/bin/assemble

In disconnected environments it is necessary to allow the developer to specify the Composer installer URL. Work done to PHP 7.1 however I plan to backport to the earlier versions.

Ability to set custom Composer download URL

---

5.6/root/usr/libexec/container-setup
7.0/root/usr/libexec/container-setup
7.1/root/usr/libexec/container-setup

Try to fix issue #189.
`chmod -R a+rwx /tmp/sessions` was run before the code moved to /usr/libexec/container-setup.

Fix permissions for /tmp/sessions

---

README.md
imagestreams/php-centos7.json
imagestreams/php-rhel7-ppc64le.json
imagestreams/php-rhel7.json

docs.openshift.org to docs.okd.io
github.com/openshift/cakephp-ex to github.com/sclorg/cakephp-ex

OKD rebranding and sclorg move

---

7.1/Dockerfile.fedora
test/run-openshift

Fedora uses by default 'event' MPM module, so switch to 'prefork'
to provide same user experience as with RHEL/CentOS image.
For more information see https://bugzilla.redhat.com/show_bug.cgi?id=1586332 .
@pkubatrh @notroj @remicollet @dustymabe Please review. Any ideas are welcomed!

Fix Fedora based image - switch back to 'prefork'

---

7.0/README.md
7.1/README.md
7.2/README.md

The environment variables in `.sti` are not injected.
Renaming `.sti` to `.s2i` fixes this problem. I guess that part of the documentation was forgotten when renaming.

Fix documentation for environment variables

---

7.0/s2i/bin/assemble
7.1/s2i/bin/assemble
7.2/s2i/bin/assemble

Move fix-permissions right after `mv`.
Reference issue:
https://github.com/sclorg/container-common-scripts/issues/119

Fix permissions for all files given in s2i

---

7.0/s2i/bin/assemble
7.0/test/run
7.1/s2i/bin/assemble
7.1/test/run
7.2/s2i/bin/assemble
7.2/test/run

Add parameter `ct_build_s2i_npm_variables`
into `run_s2i_build` function.
It checks if internal NPM_REGISTRY is set and
CA file is present. Else use public NPM registry.

Add support for internal Nexus registry

---

7.2/test/imagestreams
7.3/test/imagestreams
test/imagestreams
test/run-openshift-local-cluster
test/run-openshift-remote-cluster
test/test-lib-php.sh

This PR combines more changes:
- add image stream test
- adopts new functions refactored in https://github.com/sclorg/container-common-scripts/pull/155/files
- enables tests to be run in a remote OCP4 cluster

Use refactored functions and enable testing in remote OCP4

---

7.2/test/run
7.3/test/run

In case some of the test fails, test suite finishes
with TESTSUITE_RESULT value.
check_result function is used for setting TESTSUITE_RESULT value.

container tests finish with TESTSUITE_RESULT

---

test/run

This commit moves `ct_enable_cleanup` after sourcing `test-lib.sh`.
and the test suite is fixed so it reports failure properly.
Similar fix in s2i-perl-container https://github.com/sclorg/s2i-perl-container/pull/191

Fix calling ct enable cleanup

---

test/check_imagestreams.py
test/run-openshift-local-cluster

This commit adds check for the latest version in imagestreams.
If the latest version is not present in imagestreams, then the test fails.

Test the latest version in imagestreams

---

README.md
test/run

The images are EOL since Nov 2020.
Images for RHEL8 are still supported.

Deprecate php-7.2 for RHEL7 and CentOS7

---

imagestreams/php-centos.json

Use quay.io as a source of the images to avoid Docker Hub ratelimiting where possible

imagestream: point centos7 images to quay.io

---

7.3/Dockerfile.rhel8
7.4/Dockerfile.rhel8

zip extension is missing for php 7.3 and 7.4 rhel8 based containers

php-pecl-zip package added for rhel-8 containers for 7.3 and 7.4

---

7.3/README.md
7.3/s2i/bin/assemble
7.4/README.md
7.4/s2i/bin/assemble

Proposal from https://bugzilla.redhat.com/1901768
Small changes + documentation
Can use:
COMPOSER_VERSION=1 for latest version 1 (1.10.17 for now)
COMPOSER_VERSION=2 for latest version 2 (2.0.7 for now)
COMPOSER_VERSION=snapshot for git snapshot
COMPOSER_VERSION=preview for beta version (none for now, so 2.0.7)
COMPOSER_MAJOR_VERSION=version=x.y.z for any specific version
Default is to use the latest stable release (2.0.7 for now)
#320

Bug1901768

---

imagestreams/php-centos.json
imagestreams/php-rhel-aarch64.json
imagestreams/php-rhel.json

Non-groupified objects were deprecated in OCP 4.7.

Use groupified apiVersion

---

test/run-openshift-local-cluster

The container-common-scripts contain fix for  the CentOS 7 - OpenShift 3 tests.

Fix OpenShift tests

---

7.3/README.md
README.md
imagestreams/php-rhel-aarch64.json
imagestreams/php-rhel.json
test/run-openshift-local-cluster

This pull request removes PHP-7.3 for RHEL8 from upstream repositories.
It updates:
- imagestreams files
- README.md file
- 7.3/README.md file
- comment out `test_latest_imagestreams`

php-7.3 reached EOL for RHEL8.

---

.github/workflows/docker-tests.yml

Let's use c9s compose back again, so we have access to c9s packages built in koji.

Use public c9s compose

---

.github/workflows/build-and-push.yml
8.0/Dockerfile.fedora
8.0/root/usr/libexec/container-setup
8.0/root/usr/share/container-scripts/php/common.sh

This pull request adds support for php 8.0 for the Fedora container.
As soon as it is merged, the php-8.0 container will be available in quay.io repository https://quay.io/repository/fedora/php-80

Support fedora for version 8.0

---

8.0/Dockerfile.rhel9
8.0/README.md
8.0/root/usr/libexec/container-setup
README.md

This pull request adds support for building and testing PHP-80 container on RHEL9 host.
It also updates README.md files with references to Quay.io
Diff between C9S and RHEL9 Dockerfile is here:
```bash
$ diff 8.0/Dockerfile.c9s 8.0/Dockerfile.rhel9
1c1
< FROM quay.io/sclorg/s2i-base-c9s:c9s
---
> FROM ubi9/s2i-base:1
10c10
< # This image provides an Apache 2.4 + PHP 7.4 environment for running PHP applications.
---
> # This image provides an Apache 2.4 + PHP 8.0 environment for running PHP applications.
35c35
<       name="sclorg/${NAME}-${PHP_VER_SHORT}-c9s" \
---
>       name="ubi9/${NAME}-${PHP_VER_SHORT}" \
40c40
<       usage="s2i build https://github.com/sclorg/s2i-php-container.git --context-dir=${PHP_VERSION}/test/test-app sclorg/${NAME}-${PHP_VER_SHORT}-c9s sample-server" \
---
> …
```

Support build and testing php-80 on RHEL9 host

---

7.3/test/test-openshift.yaml
7.4/test/test-openshift.yaml
8.0/test/test-openshift.yaml
test/run-openshift-remote-cluster
test/test-lib-php.sh
test/test-openshift.yaml

This pull request add support for testing php-container in CVP pipeline
* `common` directory is updated into latest
* `test-openshift.yaml` file is added into `test`, `7.3`, `7.4` and `8.0` directories
* `test-lib-php.sh` add support for testing imagestreams in RHEL8
* `run-openshift-remote-cluster` tags image into OpenShift 4

Support cvp

---

7.3/test/test-openshift.yaml
7.4/test/test-openshift.yaml
8.0/test/test-openshift.yaml

Use test-openshift.yaml from common dir.

---

7.3/Dockerfile.fedora
7.3/Dockerfile.rhel8
7.4/Dockerfile.fedora
7.4/Dockerfile.rhel8
8.0/Dockerfile.c9s
8.0/Dockerfile.fedora
8.0/Dockerfile.rhel8
8.0/Dockerfile.rhel9

Otherwise when a wrong stream is installed, it's only found by scl test, which is too late in the process and might even go through uncought, especially when the scl test is removed for non-SCL distros at some point.

Add a test in Dockerfile directly to check php version

---

7.3/Dockerfile
7.3/Dockerfile.fedora
7.3/Dockerfile.rhel7
7.3/Dockerfile.rhel8
7.4/Dockerfile
7.4/Dockerfile.fedora
7.4/Dockerfile.rhel7
7.4/Dockerfile.rhel8
8.0/Dockerfile.c9s
8.0/Dockerfile.fedora
8.0/Dockerfile.rhel8
8.0/Dockerfile.rhel9
8.1/Dockerfile.c9s
8.1/Dockerfile.fedora
8.1/Dockerfile.rhel8
8.1/Dockerfile.rhel9

Fixes #302.
We I opened this issue, I needed to add custom packages to these s2i images, but then I needed to fork this repo and editing the package list, or to create a Dockerfile and adding custom packages : in both case I needed to maintain a side repo where we could just have a build argument for that. I could create then a custom build in OpenShift, point it to this repo and add build arg.
In every Dockerfile, I moved the `INSTALL_PKGS` as a build arg. It allows people to rebuild these s2i images and adding with custom packages without having to fork and edit this repo.
None, because I added all the listed packages as a default value for this argument. People who don't care won't be affected.
The original issue is nearly three years old. At that time I had a clear idea of what to do, …

feat: INSTALL_PKGS is now a build argument

---

.github/workflows/container-tests.yml
.github/workflows/openshift-tests.yml
7.3/README.md
7.4/README.md
8.0/README.md
8.1/README.md
8.2/README.md
README.md
imagestreams/imagestreams.yaml
imagestreams/php-centos.json
imagestreams/php-rhel.json
test/run-openshift-remote-cluster

This pull request deprecates building, testing PHP container in RHEL-7.
The pull request is separated to two commits:
1) Remove RHEL-7 from CI and disable building and testing.
2) Update README's so that RHEL-7 -> RHEL-8 and CentOS7 -> CentOS Stream 9

Remove RHEL-7 - EOL June 2024

---

.github/workflows/container-tests.yml

This pull request allows testing s2i-php-container on CentOS Stream 10 host.
See similar PR: 
https://github.com/sclorg/httpd-container/pull/223
https://github.com/sclorg/mariadb-container/pull/251

Support testing s2i-php-container on CentOS Stream  10

---

.github/workflows/build-and-push.yml
8.3/README.md
README.md

This pull request updates README's
and allow building and push php-83 on quay.io

Add build and push for fedora

---

7.4/test/test_helm_cakephp_application.py
7.4/test/test_helm_chart_imagestreams.py
8.0/test/test_helm_cakephp_application.py
8.0/test/test_helm_chart_imagestreams.py
8.1/test/test_helm_cakephp_application.py
8.1/test/test_helm_chart_imagestreams.py
8.2/test/test_helm_cakephp_application.py
8.2/test/test_helm_chart_imagestreams.py
8.3/test/test_helm_cakephp_application.py
8.3/test/test_helm_chart_imagestreams.py
test/test_helm_cakephp_application.py
test/test_helm_chart_imagestreams.py

This pull request adds support for testing Helm Charts stored in https://github.com/sclorg/helm-charts repository.

Add support for testing Helm Charts in PHP container.

---

.github/workflows/build-and-push.yml

Add support for building and pushing php-83 image to quay.io/sclorg organization

Add support for building and pushing php-83 image to quay.io/sclorg

---

.github/workflows/container-tests.yml
.github/workflows/openshift-pytests.yml
.github/workflows/openshift-tests.yml
Makefile
README.md

This pull request deprecates PHP-80 image from RHEL8.
It reached EOL in Nov 2024.
- The first commit adds `.exclude-rhel8` file into 8.0 directory
- The documentation is updated with deprecation 7.3 which is completely EOL. It is removed also from Makefile.

Deprecation PHP-80 image on RHEL8

---

8.3/Dockerfile.c10s
8.3/Dockerfile.c9s
8.3/Dockerfile.fedora
8.3/Dockerfile.rhel9

Main benefit: will install the extension, whatever the package name is, and latest version, ex:
- zip => php-zip => php-pecl-zip
- json => php-pecl-json => php-json => php-common (since 8.0)
- redis => php-pecl-redis3 => php-pecl-redis5 => php-pecl-redis6
- etc
By packaging Guidelines, the `php-<extname>` is always provided and is the only reliable name
https://docs.fedoraproject.org/en-US/packaging-guidelines/PHP/#requires-provides-c

use ext name instead of pkg name, and add redis

---

8.3/Dockerfile.rhel10
8.3/README.md
8.3/root/usr/libexec/container-setup
8.3/s2i/bin/run
README.md
test/run

This pull request enables building and testing s2i-php-container on RHEL10 host.
The pull request is separated into 2 commits:
1) The first one adds 8.3/Dockerfile.rhel10
2) The second one updates README.md files with RHEL10 information

Building and testing container on RHEL10 host

---

8.0/root/opt/app-root/etc/php.ini.template
8.1/root/opt/app-root/etc/php.ini.template
8.2/root/opt/app-root/etc/php.ini.template
8.3/root/opt/app-root/etc/php.ini.template

* assert.quiet_eval was removed in 8.0
* mail.mixed_lf_and_crlf was added in 8.2
* mysqli.reconnect was removed in 8.2
* other assert.* are deprecated in 8.3

clean-up ini

---

8.3/Dockerfile.rhel10

Certificates are not need at all in Dockerfile.
Remove these certificates.
See JIRA: https://issues.redhat.com/browse/ENGCMP-5283

s2i-core and s2i-base images are available from unauthenticated registries

---

test/test-lib-php.sh
test/test_php_deploy_templates.py
test/test_php_s2i_imagestreams.py
test/test_php_s2i_integration.py
test/test_shared_helm_cakephp_application.py

Do not test imagestreams on RHEL10 yet.
They do not exist.
Fix PyTest API test suite. Function has been renamed.

Do not tests imagestreams on RHEL10 yet

---

.github/workflows/auto-merge-on-demand.yml
test/test-lib-php.sh

Fix regular expression for proper return 'rhel' name from 'rhel10'
All expression returns 'rhel1'. The new expression returns proper name

Fix regular expression for proper return 'rhel' name from 'rhel10'

---

test/test-lib-php.sh
test/test_php_deploy_templates.py
test/test_shared_helm_cakephp_application.py
test/test_shared_helm_chart_imagestreams.py

Do not test PHP Openshift tests
