sclorg/s2i-php-container

5.5/.sti/bin/assemble, 5.5/.sti/bin/run, 5.5/Dockerfile, 5.5/Dockerfile.rhel7, 5.5/contrib/httpd.conf, 5.5/contrib/httpdconf.sed, 5.5/test/run
Initial attempt at supporting non-root user
=> Support random uid

hack/build.sh
This reverts commit 122d88e3ad2cf29b92abaeda3b103af11fc809c6.
=> Revert "squash on build"

5.5/.sti/bin/usage, README.md
=> Updated docs and usage with new flag naming in STI

5.5/Dockerfile, 5.5/contrib/httpdconf.sed, README.md
=> Adding support for .htaccess file in app source

5.5/.sti/bin/assemble, 5.5/.sti/bin/run, 5.5/contrib/src/.bashrc, Makefile, hack/build.sh
For details, see: https://github.com/openshift/sti-base/pull/35
=> Remove bashrc sourcing in STI scripts

5.5/Dockerfile.rhel7
=> Added mandatory labels

5.5/Dockerfile, 5.5/Dockerfile.rhel7, 5.6/Dockerfile, 5.6/Dockerfile.rhel7
fix for https://bugzilla.redhat.com/show_bug.cgi?id=1253248
=> fix session dir permissions

README.md
Since php picks up changes in source by default, there is nothing else just update README && official docs.
@mfojtik @bparees thoughts ?
=> Update README with hot deploy

5.5/contrib/etc/php.d/opcache.ini.template, 5.5/s2i/bin/run, 5.6/contrib/etc/php.d/10-opcache.ini.template, 5.6/s2i/bin/run, README.md
Updated  both versions + docs.
@bparees PTAL
=> Hot deploy env var

5.5/s2i/bin/assemble, 5.6/s2i/bin/assemble
=> Fix directory permissions after assemble is complete

5.6/Dockerfile.rhel7
Related: openshift/postgresql/pull/75
=> Sync Red Hat build service labels

5.6/s2i/bin/usage
=> Fix image name in s2i usage message

5.5/README.md, 5.6/README.md
=> Updates README.md file to include composer

5.5/s2i/bin/assemble, 5.6/s2i/bin/assemble
fixes https://github.com/openshift/sti-php/issues/73
=> remove --no-scripts composer argument

5.5/contrib/etc/httpdconf.sed, 5.6/contrib/etc/httpdconf.sed
fixes https://github.com/openshift/s2i-php/issues/93
=> send error log to stdout

5.5/README.md, 5.5/contrib/etc/php.ini.template, 5.5/s2i/bin/run, 5.6/README.md, 5.6/contrib/etc/php.ini.template, 5.6/s2i/bin/run
@bparees Would be nice to have it enabled as 5.5 does. PTAL
=> Enable short_open_tags

5.5/README.md, 5.5/s2i/bin/usage, 5.6/README.md, 5.6/s2i/bin/usage, README.md
=> Replace sti with s2i

5.5/README.md, 5.5/contrib/etc/conf.d/00-documentroot.conf.template, 5.5/contrib/etc/httpdconf.sed, 5.5/s2i/bin/run, 5.6/README.md, 5.6/contrib/etc/conf.d/00-documentroot.conf.template, 5.6/contrib/etc/httpdconf.sed, 5.6/s2i/bin/run
Much simpler then my original concept #107
=> Adding DOCUMENTROOT environment variable

5.6/contrib/etc/php.ini.template
=> modify variables_order to populate $_ENV

5.5/Dockerfile.rhel7, 5.6/Dockerfile.rhel7
Labels now should follow spec at https://github.com/projectatomic/ContainerApplicationGenericLabels/blob/master/vendor/redhat/labels.md
=> New labels for OSBS

5.5/Dockerfile, 5.5/Dockerfile.rhel7, 5.6/Dockerfile, 5.6/Dockerfile.rhel7
Please add the php gmp module to the s2i image.
=> Add php-gmp module

README.md
=> Added mention of php 7.0 to README

5.5/test/run, 5.6/test/run, 7.0/test/run
This may lead to conflicts with tests for different repository.
@hhorak @bparees Please take a look.
=> Do not publish a container's port(s) to the host in tests

5.6/test/run, 7.0/test/run, 7.1/test/run
Similarily to: https://github.com/sclorg/s2i-python-container/pull/229
=> tests: replace removed s2i flag

5.6/Dockerfile, 5.6/Dockerfile.rhel7, 5.6/README.md, 7.0/Dockerfile, 7.0/Dockerfile.rhel7, 7.0/README.md, 7.1/Dockerfile, 7.1/Dockerfile.rhel7, 7.1/README.md, README.md
This Pull Request contains couple documentation updates from container-images/php repo.
After merging this Pull Request the repo container-images/repo will be marked as obsolete.
=> Merge from container-images/php repo

5.5/s2i/bin/assemble, 5.6/s2i/bin/assemble, 7.0/s2i/bin/assemble, 7.1/s2i/bin/assemble
We're getting periodic test flakes on Origin due to failure to download https://getcomposer.org/installer, it would be useful to see if a retry helps
https://github.com/openshift/origin/issues/16772
@bparees
=> retry https://getcomposer.org/installer download if it fails

5.6/root/usr/libexec/container-setup, 7.0/root/usr/libexec/container-setup, 7.1/root/usr/libexec/container-setup
=> Fix UID for /tmp/sessions and other files

5.6/test/run, 7.0/test/run, 7.1/test/run, test/test-app/session_test.php
Follow up of PR #193. Add test cases for the issue #189.
=> Add test app and test cases for /tmp/session permissions

5.6/root/opt/app-root/etc/scl_enable, 7.0/root/opt/app-root/etc/scl_enable, 7.1/root/opt/app-root/etc/scl_enable
This will allow us to update to newer nodejs smoothly.
=> Use a variable for NodeJS SCL name

7.0/test/run, 7.1/test/run
Just checks whether npm is available and is able to install some package.
=> Add test for npm availability

7.0/README.md, 7.1/README.md
=> Document npm purpose and no guarantee for version

7.0/Dockerfile, 7.1/Dockerfile
It is not necessary to use testing repo now anymore, all packages are in released repo already.
=> Use released repos only

7.0/README.md, 7.1/README.md
change part about image extending to what is used in the code.
Fixes: #213
=> Fix README

imagestreams/php-rhel7-ppc64le.json
Adding this rhel7 php 7.1 imagestream that will support ppc64le.
=> imagestream definition for rhel based php 7.1 on ppc64le

imagestreams/php-centos7.json, imagestreams/php-rhel7.json
per request from @siamaksade from OpenShift PM, this PR removes EOF version from the imagestream file
@hhorak @bparees
=> remove versions that are EOL

imagestreams/php-centos7.json, imagestreams/php-rhel7-ppc64le.json, imagestreams/php-rhel7.json
This pull request removes a minor typo for all the image stream descriptions.
=> Removing Version Typo from Image Stream Descriptions

7.3/Dockerfile, 7.3/Dockerfile.fedora, 7.3/root/usr/share/container-scripts/php/common.sh, test/run-openshift-local-cluster
=> enable centos7/rhel7/fedora builds for 7.3

imagestreams/php-rhel7-s390x.json
Similar PR to sclorg/mariadb-container#115
=> Add imagestream file for s390x

7.2/test/run, 7.3/test/run
This commit runs all tests by default and report only FAILUREs.
=> Run all tests by default

imagestreams/php-rhel-aarch64.json
Obsoletes https://github.com/sclorg/s2i-php-container/pull/308
=> Add aarch64 imagestreams

7.2/Dockerfile, 7.2/README.md, 7.3/Dockerfile, 7.3/README.md, 7.4/Dockerfile, 7.4/README.md, README.md
This commit updates Dockerfile with Quay.io registry
It updates also README.md files with Quay.io and
adds the latest container-common-scripts
=> Support Quay.io

.github/workflows/rhel7-tests.yml
=> Fix branch for RHEL7 workflow

.github/workflows/rhel7-tests.yaml, .github/workflows/rhel8-tests.yaml
=> Use TMT/FMF unique names

.github/workflows/build-and-push.yml
=> Add support for building and pushing image into Quay.IO

.github/workflows/openshift-tests.yml
=> Support Testing Farm as GitHub Action for OpenShift tests

8.0/Dockerfile.rhel8
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2092356
=> RPM uses a wrong file in the config, fix it in the container

.github/workflows/container-tests.yml, .github/workflows/openshift-tests.yml
=> Testing single versions in CI for container and openshift tests

8.0/Dockerfile.rhel8, 8.0/s2i/bin/run
=> Allow building and testing RHEL8 PHP-80

test/test-lib-php.sh
This pull request adds support for testing imagestreams also on RHEL9
=> Support rhel9 imagestream

.github/workflows/build-and-push.yml, .github/workflows/container-tests.yml, .github/workflows/openshift-tests.yml
Needed for #393 
@phracek @zmiklank PTAL
=> update github actions for 8.1

7.4/root/usr/libexec/container-setup, 8.0/root/usr/libexec/container-setup, 8.1/root/usr/libexec/container-setup, test/run
=> set correct permissions for config files

test/run-openshift-local-cluster
This pull request fixes OpenShift 3 failures.
=> Fix rhel7 ocp3

8.0/root/usr/libexec/container-setup, 8.1/root/usr/libexec/container-setup
=> fix permissions for fpm configuration

.github/workflows/build-and-push.yml, .github/workflows/container-tests.yml, .github/workflows/openshift-tests.yml, 7.3/cccp.yml, 7.4/cccp.yml
move fedora images to fresh fedora version
remove cccp.yaml files.
=> disable rebuilds and testing for centos7 images

.github/workflows/container-tests.yml, .github/workflows/openshift-tests.yml
=> Add support for testing PHP 8.2

.github/workflows/build-and-push.yml
=> Enable building and pushing image to Quay.io

.github/workflows/build-and-push.yml
=> remove 7.4 c9s image from build and push since we do not support it

imagestreams/php-centos.json, imagestreams/php-rhel-aarch64.json, imagestreams/php-rhel.json
This pull request adds imiagestreams for PHP-81 and RHEL9/UBI9
=> Add imagestreams for RHEL9 and PHP-81

test/run-openshift-remote-cluster, test/test-lib-php.sh
This pull request adds testing cake-php-ex repository properly
in s2i-php-container
=> Add testing cake-php ex repositories properly

.github/workflows/openshift-tests.yml, imagestreams/imagestreams.yaml, imagestreams/php-centos.json, imagestreams/php-rhel-aarch64.json, imagestreams/php-rhel.json
This PR removes tag "7.3" as it not standard for other sclorg images. I also removes tring `"supports":"php:8.0,php"` from the tag. Could that cause a problem?
=> Imagestream generator

imagestreams/imagestreams.yaml, imagestreams/php-rhel.json
we need to maintain it for the lifetime of this image.
=> re-add previously removed "7.3" IS tag

.github/workflows/openshift-pytests.yml
=> Add GitHub Action for running PyTest in OpenShift 4

.github/workflows/openshift-pytests.yml
=> Update openshift-pytests.yml with correct versions

test/test_deploy_templates.py, test/test_latest_imagestreams.py, test/test_s2i_imagestreams.py, test/test_s2i_integration.py
=> Use VERSION instead of SINGLE_VERSION like we do in whole org

8.0/test/run-openshift
=> Remove obsoleted files

.github/auto-merge.yml, .github/workflows/auto-merge-on-demand.yml, .github/workflows/auto-merge.yml, .github/workflows/pr-metadata.yml
This pull request adds support for PR detection what is missing.
Like CI failed, Missing review, etc.
=> Allow PR analysis, add support for auto-merger-bot

.github/workflows/build-and-push.yml
=> Use proper useraccount and token for pushing to c10s

.github/workflows/build-and-push.yml
This pull request enable building and testing PHP-83 container image
on C9S and RHEL9.
The second part of this pull request is to enable building and pushing PHP-83 container image
to quay.io/sclorg organization
=> Enable testing php83 rhel9
